Oh, hey, I should probably put something here.

* εφφαθα
Be ye opened.

* unsorted
Ugh, this github orgmode reader doesn't believe in linebreaks.
 That's because orgmode's HTML output doesn't.

Apologies to anyone trying to read this. I use org-mode wrong, and I'm not going to change soon.

** Environment
I'm tempted to add a "get" method which equals "read".
I'm tempted to add a "curry" method or something.

** Server
It's been too long since I've used this, so I need some documentation.
That's convenient, since you need some documentation too!

** Starting over
let's do the simplest thing we can: let the admin eval strings
first, we'll need to store the strings (for convenience)
 we don't have to, but it'll be nicer this way

*** string list
anonymous can append a string to the list
**** admin can
read
write
execute
delete
**** anonymous can
GET the form to submit a new string
POST to add the string to the end of the list
**** HTTPS
access the append form

admin secure-only cookie
 session token (not password)
  how should I generate that?
 do not allow insecure admin access
  enable that later
***** actions
GET read
DELETE
POST
 exec
 persist
**** URLs
/ index
/index index
/index.html index
/append GET form
/append POST append
/admin/ GET listing
/admin/$num GET read $num-th element
/admin/$num DELETE remove $num-nth element, moving others down?
/admin/$num/exec POST run it, returning the string representation of the immediate return
 unless it returns a promise? make that a next-time feature
/admin/$num/persist POST save it to a directory somewhere to load when the server starts
 make that a next-time feature
/admin/login GET login form
/admin/login POST generate session and set HTTPS-only cookie
